# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/l10n/*.dart" # Ref: https://zenn.dev/aryzae/articles/0555959ac3800e
    - '**/firebase_options*.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    require_trailing_commas: false
 